{% set name = "blend2d" %}
{% set version = "beta12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: blend2d-d22006b7c16abf6d00752778bf87315208980c20.tar.gz
    url: https://github.com/blend2d/blend2d/archive/d22006b7c16abf6d00752778bf87315208980c20.tar.gz
    sha256: 106556ab5357fb25b9e7d00bb616420fbfee238ebfb2d9f0a14e0a41aaa6ed7e
    folder: blend2d

  - url: https://github.com/asmjit/asmjit/archive/1491d5f2ea0b6b398a63f250e7456a032866320f.tar.gz
    fn: asmjit-1491d5f2ea0b6b398a63f250e7456a032866320f.tar.gz
    sha256: e58f017994725f0cc490b9a6dd1ca2d8f8e7c60154b83e616927a23fc859b058
    folder: asmjit

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja    

test:
  commands:    
    - if not exist %LIBRARY_LIB%\\blend2d.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\blend2d.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\blend2d.h exit 1  # [win]
    - test -f $PREFIX/lib/libblend2d$SHLIB_EXT  # [unix]   
    

about:
  home: https://github.com/blend2d/blend2d/
  license: Zlib
  license_file: blend2d/LICENSE.md
  summary: '2D Vector Graphics Engine Powered by a JIT Compiler'

  
  description: |
    Blend2D is a high performance 2D vector graphics engine written in C++ and
    released under the Zlib license. It has a built-in JIT compiler that
    generates optimized pipelines at runtime. Additionally, the engine features
    a new rasterizer that has been written from scratch. It delivers superior
    performance while quality is comparable to rasterizers used by AGG and
    FreeType. The performance has been optimized by using an innovative approach
    to index data that is built during rasterization and scanned during
    composition. The rasterizer is robust and excels in rendering complex vector
    art and text.
  doc_url: https://blend2d.com/doc/
  dev_url: https://github.com/blend2d/blend2d/
extra:
  recipe-maintainers:
    - tillsten
    
